<?xml version="1.0" encoding="utf-8"?>

<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <StaticWebAssetBasePath>App_Plugins/$(AssemblyName)</StaticWebAssetBasePath>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <VersionPrefix>17.0.0-beta001</VersionPrefix>
    <VersionSuffix Condition="'$(Configuration)'=='Debug'">build$([System.DateTime]::UtcNow.ToString(`yyyyMMddHHmm`))</VersionSuffix>
    <Company>Limbo</Company>
    <Authors>Anders Bjerner</Authors>
    <Copyright>Copyright © $([System.DateTime]::UtcNow.ToString(`yyyy`))</Copyright>
    <Title>Skybrud Redirects Import</Title>
    <Description>Import and export addon for Skybrud Redirects.</Description>
  </PropertyGroup>

  <!-- Information for the NuGet package -->
  <PropertyGroup>
    <PackageId>Skybrud.Umbraco.Redirects.Import</PackageId>
    <PackageTags>Skybrud, Umbraco, Redirects, Import, Export, Limbo, Umbraco-Marketplace</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://packages.limbo.works/skybrud.umbraco.redirects.import/</PackageProjectUrl>
    <PackageIcon>Limbo.png</PackageIcon>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/skybrud/Skybrud.Umbraco.Redirects.Import</RepositoryUrl>
  </PropertyGroup>

  <!-- Include additional metadata in the assembly -->
  <ItemGroup>
    <AssemblyMetadata Include="PackageProjectUrl" Value="https://packages.limbo.works/skybrud.umbraco.redirects.import/" />
    <AssemblyMetadata Include="DocumentationUrl" Value="https://packages.limbo.works/skybrud.umbraco.redirects.import/docs/v17/" />
    <AssemblyMetadata Include="NuGetUrl" Value="https://www.nuget.org/packages/Skybrud.Umbraco.Redirects.Import" />
    <AssemblyMetadata Include="UmbracoMarketplaceUrl" Value="https://marketplace.umbraco.com/package/skybrud.umbraco.redirects.import" />
  </ItemGroup>

  <!-- Include NuGet dependencies -->
  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Skybrud.Csv" Version="0.0.3" />
    <PackageReference Include="Skybrud.Essentials" Version="1.1.63" />
    <PackageReference Include="Skybrud.Umbraco.Redirects" Version="17.0.1" />
    <PackageReference Include="Umbraco.Cms.Core" Version="[17.0.0,17.999)" />
    <PackageReference Include="Umbraco.Cms.Web.Website" Version="[17.0.0,17.999)" />
  </ItemGroup>

  <!-- Include package icon for NuGet -->
  <ItemGroup>
    <Content Include="../build/Limbo.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <!-- Generate XML documentation -->
  <PropertyGroup>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>

</Project>
