using System;

namespace Skybrud.Umbraco.Redirects.Import.Exporters.Xlsx {

    /// <summary>
    /// Class representing the result of an export of redirects to an <strong>XLSX</strong> file.
    /// </summary>
    public class XlsxExportResult : IExportResult {

        private readonly byte[] _bytes;

        #region Properties

        /// <summary>
        /// Gets the unique key of the export result.
        /// </summary>
        public Guid Key { get; }

        /// <summary>
        /// Gets the content type of the file generated by the result.
        /// </summary>
        public string ContentType { get; }

        /// <summary>
        /// Gets the file name of the file generated by the result.
        /// </summary>
        public string FileName { get; }

        #endregion

        #region Constructors

        /// <summary>
        /// Initializes a new instance based on the specified <paramref name="key"/> and <paramref name="bytes"/> object.
        /// </summary>
        /// <param name="key">The unique key.</param>
        /// <param name="bytes">An array of <see cref="byte"/> representing the XLSX file.</param>
        public XlsxExportResult(Guid key, byte[] bytes) {
            Key = key;
            _bytes = bytes;
            ContentType = RedirectsImportConstants.ContentTypes.Xlsx;
            FileName = $"Redirects_{DateTime.UtcNow:yyyyMMddHHmmss}.xlsx";
        }

        #endregion

        #region Member methods

        /// <summary>
        /// Returns the bytes of the exported file.
        /// </summary>
        /// <param name="options">The export options.</param>
        /// <returns>An array of <see cref="byte"/>.</returns>
        public byte[] GetBytes(IExportOptions options) {
            return _bytes;
        }

        #endregion

    }

}